name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
              programming_paradigms.tex
              software_patterns.tex
          latexmk_use_xelatex: true
          args: -pdf -interaction=nonstopmode -shell-escape
          working_directory: latex
          extra_system_packages: "py-pygments"
