name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
              programming_paradigms.tex
              software_patterns.tex
          latexmk_use_xelatex: true
          args: -f -pdf -interaction=nonstopmode -shell-escape -output-directory=build
          working_directory: latex
          extra_system_packages: "py-pygments"
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            latex/build/programming_paradigms.pdf
            latex/build/software_patterns.pdf
